### ISSUE TITLE
Issue with HelpfulRobotDataTask

### ISSUE THREAD

**Issue by sunnysideupdevs** [silverstripe/addons.silverstripe.org#136] opened 2016-10-31 21:43 UTC
I was puzzled why this module shows as not having as CONTRIBUTING.md

http://addons.silverstripe.org/add-ons/sunnysideup/ecommerce_countries

It clearly has one in the Git repository
https://github.com/sunnysideup/silverstripe-ecommerce_countries

and the return from  https://helpfulrobot.io/sunnysideup/ecommerce_countries indicates
it has found the CONTRIBUTING.md file:

{"name":"sunnysideup\/ecommerce_countries","inspections":[{"has_change_log_file":true,"has_code_folder":true,"has_code_of_conduct_file":false,"has_contributing_file":true,"has_docs_folder":true,"has_editor_config_file":true,"has_git_attributes_file":false,"has_license_file":true,"has_readme_file":true,"has_scrutinizer_file":false,"has_scrutinizer_setup":false,"has_tests_folder":false,"has_travis_file":true,"has_travis_setup":true,"type":"silverstripe-module","score":62}],"badge":"https:\/\/helpfulrobot.io\/sunnysideup\/ecommerce_countries\/badge","points":{"has_change_log_file":2,"has_code_folder":1,"has_code_of_conduct_file":3,"has_contributing_file":2,"has_docs_folder":8,"has_editor_config_file":1,"has_git_attributes_file":1,"has_license_file":5,"has_readme_file":3,"has_scrutinizer_file":1,"has_scrutinizer_setup":3,"has_tests_folder":8,"has_travis_file":1,"has_travis_setup":3,"type":0}}

**Comment by dhensby** [comment] 2016-11-04 16:15
cc @helpfulrobot

**Comment by camfindlay** [comment] 2016-11-11 02:24
fixed - still need to investigate why it was bugging out.

**Comment by robbieaverill** [comment] 2016-12-12 21:48
Closing as the issue is now fixed. Please reopen if you experience it again.

**Closed by robbieaverill** 2016-12-12 21:48 UTC
