### ISSUE TITLE
The data displayed doesn't reflect the default branch

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/addons.silverstripe.org#126] opened 2016-04-09 11:14 UTC
See this discussion: https://groups.google.com/forum/m/#!topic/silverstripe-dev/sgFpfrPza1U

Looks like at least the README file doesn't necessarily reflect the default branch. In the case of the language-prefix module, the README of a test branch is displayed, making it look like the module itself is in test phase, which it is not! :) and neighter does it mirror the situation on Packagist.

Addons: http://addons.silverstripe.org/add-ons/martimiz/silverstripe-languageprefix

The master branch, which is actually the default on Github,  is the 'open' one, so that is ok, but the README and possibly the score (although the latter may be because the site isn't regularly updated?)  belong to another branch.

[edit] could it be that it is getting the data from the last created branch instead of the default?

Martine

**Comment by camfindlay** [comment] 2016-04-10 21:04
Thanks @Martimiz - will have a look into this. Also if you want to look over the code here feel free if you can spot a problem and know a fix we can look to merge and deploy pretty quickly.

**Comment by Martimiz** [comment] 2016-04-11 10:00
Hi Cam, 
I have been looking at it already, but it's kinda hard, especially as this is not a module you can test unless you've got access to some internal SilverStripe stuff, as the README states...

And I'm not keen on sending PR's that I can't test :( So I'll definitely have another look, but highly appreciate it if you could find the time too :)

Thanks!!!

**Comment by camfindlay** [comment] 2016-04-12 00:20
Would a vagrant box help?

**Comment by Martimiz** [comment] 2016-04-13 08:20
For now I've actually downloaded the code and am reading through it to make out the flow :) I'll let you know :)

**Comment by nglasl** [comment] 2016-06-22 00:44
I encountered what seems to be this issue today, so I thought I should bring it up here. Basically this README displays as **release 2.0.2**..

http://addons.silverstripe.org/add-ons/nglasl/silverstripe-descriptive

However, if you have a look over here, you'll notice **release 2.1.2**, which it has been on for a long while..

https://github.com/nglasl/silverstripe-descriptive

This can be explained if you look over at the **2.0** branch, since this has **release 2.0.2**.

**Comment by robbieaverill** [comment] 2017-04-10 03:06
Relates to #103

**Comment by robbieaverill** [comment] 2018-05-13 22:33
Closing as a duplicate of #103

**Closed by robbieaverill** 2018-05-13 22:33 UTC
