### ISSUE TITLE
Default search disappears when I select 'modules'

### ISSUE THREAD

**Issue by mandrew** [silverstripe/addons.silverstripe.org#74] opened 2014-04-17 03:27 UTC
Selected 'addons' and I get all themes and modules by default which is ok. I then wanted to only view current modules so choose the 'modules' option from the dropdown and clicked search. No modules are returned in the search but there was pagination showing? (see screenshot). The same process but choosing 'themes' at least returns some themes.

![add-ons__silverstripe_add-ons](https://cloud.githubusercontent.com/assets/343938/2727797/28d34840-c5df-11e3-955f-0df1956b33e4.jpg)

**Comment by robbieaverill** [comment] 2016-12-07 20:07
Hi @mandrew - I can't reproduce this now, so will close the issue. If you see it again, feel free to reopen it.

**Closed by robbieaverill** 2016-12-07 20:07 UTC
